### ISSUE TITLE
go build does not work in root directory

### ISSUE THREAD

**Issue by craftamap** [knoxite/knoxite#102]
When executing `go build` in the root directory of knoxite, no binary is generated.
However, running `go build github.com/knoxite/knoxite/cmd/knoxite` or running `go build` in `cmd/knoxite` does work.
This means that running `go get` also does not install knoxite currently.

While I do not like the behavior, that the binary cannot be generated in the root directory, there may is a actual reason for this. If this is the case, we should update the README.md to include current build instructions.

I also think that the current text pipeline does not check if a binary is generated.

**Comment by muesli** [comment]
This is expected. You'll have to `go get github.com/knoxite/knoxite/cmd/...`. I've updated the README in that regard just now.
