### ISSUE TITLE
Alias does not work

### ISSUE THREAD

**Issue by Signum** [knoxite/knoxite#171]
I am trying to set up a repository alias as documented in https://knoxite.com/docs/configuration-system/

```
> rm -f ~/.config/knoxite/knoxite.conf
> pwd
/root/knoxite
> knoxite config alias azure -r azurefile://itback…@file.core.windows.net/…/…
```
However when I use that shortcut "azure" Knoxite seems to think I mean an "azure" subdirectory at my current pwd.

```
> knoxite -r azure repo info
open /root/knoxite/azure/repository.knoxite: no such file or directory
```

The config file looks good to me:

```
> cat ~/.config/knoxite/knoxite.conf 
{
  "repositories": {
    "azure": {
      "url": "azurefile://itback…@file.core.windows.net/…/…",
      "compression": "",
      "tolerance": 0,
      "encryption": "",
      "store_excludes": null,
      "restore_excludes": null
    }
  }
}
```

Knoxite was built from commit 2aadc5c6d0daa7250437886056952385c2b38233 today.

**Comment by muesli** [comment]
Sorry the latest documentation hasn't been deployed on our website yet, and this flag has recently changed in master to avoid ambiguity between paths and aliases: you now have to use `-R` (uppercase) for aliases.

**Comment by penguwin** [comment]
I've quickly made a pr to update the documentation on our website (https://github.com/knoxite/website/pull/56). 
Maybe we should compose some more documentation on the differences between the `-r | --repository` and the `-R | --alias` flag to prevent further confusions.
