### ISSUE TITLE
Differences to restic?

### ISSUE THREAD

**Issue by fd0** [knoxite/knoxite#22]
Hi,

I've had a quick look at knoxite, nice work! It looks similar to [restic](https://github.com/restic/restic) and also uses the restic chunker code, that's great. I'm awfully curious though: Why did you chose to build knoxite? Did you have a look at restic before? Was there anything missing? :-)

Regarding the chunker: You're using a patched version which we discussed [here](https://github.com/restic/chunker/pull/11), please be aware that this may introduce a bug (details: http://mrekucci.blogspot.de/2015/07/dont-abuse-mathmax-mathmin.html)

**Comment by muesli** [comment]
Hey fd0!

I've stumbled upon restic & your chunker while I was hacking on knoxite. The compliments go right back at you - nice work on both projects!

Restic & knoxite are rather similar indeed: while I started knoxite out of a need for a better backup solution, it started shifting to a generic data storage tool (at least for my personal use-cases) recently. knoxite allows you to use multiple data storage backends parallely (e.g. your local disk & Amazon S3) and reed-solomon encodes the chunked data. Think of it as RAID-5/6 over multiple storage backends.

I'm also planning to finish a "proper" implementation of a knoxite storage server (see the crude beginnings in /server), which would allow you to combine a set of servers for data storage - and of course enabling them to mutually backup each others data as a side effect.

I'm certain those features could also be integrated in restic - but personally I would consider it out of scope for a pure & elegant backup solution, which is what I perceive restic to be and strive for.

As already proven by the data chunker you wrote, there might be a lot of room for sharing code between our projects here. Who knows, that might even help improve our internal APIs :-)

Thanks for pointing out the potential issue with my patched chunker. I mean to use your upstream, I just didn't have the time to come up with a PR for it, that also supports my use-case. I might be able to look into that in the next couple of days.

-Chris

**Comment by muesli** [comment]
Just for reference regarding code sharing:

https://github.com/muesli/gotable/
https://github.com/muesli/goprogressbar/

**Comment by fd0** [comment]
Thanks for explaining the differences a bit. I'd love to win you as a contributor for restic :P

**Comment by fd0** [comment]
Why did you implement printing tables and a progress bar yourself? For both there already exist several libraries?

Although I must say that I'm currently toying around with writing my own status report implementation because the other do not quite match my use case...

**Comment by muesli** [comment]
None of the progress bar implementations I've found could handle printing multiple bars at once on the screen (correctly). I must admit I didn't look for any existing table helpers,

**Comment by yonas** [comment]
@muesli Great work on knoxite. When should we use knoxite over restic? It seems restic is more maintained. There hasn't been any updates to the bulk of knoxite in over 4-5 years.
