### ISSUE TITLE
Prune snapshots

### ISSUE THREAD

**Issue by flibustenet** [knoxite/knoxite#26]
Is it possible to prune snapshots ?

**Comment by muesli** [comment]
Definitely wanted for 1.0. I already have it planned out in my head and it's probably coming in the next few days.

**Comment by muesli** [comment]
I've added a 'snapshot remove' command. Careful, this won't delete obsolete data chunks though! There will be an optional 'pack' command (and possibly an additional option for the remove-command), which wipes those chunks from storage backends.

**Comment by muesli** [comment]
The 'repo pack' command just landed in master. You can now remove a snapshot like this:

$ knoxite -r /tmp/knoxite snapshot remove [snapshot-id]

and free up disk-space by deleting obsolete chunks like this:

$ knoxite -r /tmp/knoxite repo pack

Note that we'll still have to implement this for storage backends other than the local/filesystem backend.
