### ISSUE TITLE
Add a decoding 'cat' command

### ISSUE THREAD

**Issue by muesli** [knoxite/knoxite#43]
Add a 'cat' command that decodes to stdout in classic UNIX fashion.

**Comment by penguwin** [comment]
Can be considered closed with https://github.com/knoxite/knoxite/commit/7e83f57f031c4624b97242dd1703fe8e2f1172a6 and https://github.com/knoxite/knoxite/commit/dd526d60e2f7a34e840479d447ada880587cf87c

With https://github.com/knoxite/knoxite/pull/63 the command also gets mentioned in the README.md
