### ISSUE TITLE
storage backend - multiple entries for same storage url

### ISSUE THREAD

**Issue by sedlund** [knoxite/knoxite#45]
After trying to add an s3 bucket multiple times it would error with:
Storing repository failed

But I see that they show up when doing a 'repo info':

 knoxite -r ~/knoxite -p test repo info

Storage URL                                                                                                Available Space
--------------------------------------------------------------------------------------------------------------------------
/home/user/knoxite                                                                                              1.00 GiB
http://s3.amazonaws.com/mybucket                                                                                     0B
s3://id:key@s3.amazonaws.com/us-east-1/mybucket               0B
s3://id:key@s3.amazonaws.com/us-east-1/mybucket               0B
s3://id:key@s3.amazonaws.com/us-east-1/mybucket               0B
s3://id:key@s3.amazonaws.com/us-east-1/mybucket               0B

---

there should also be a way to remove them I suppose

**Comment by penguwin** [comment]
Fixed by: a69ec94d5ee6d9ba827aeb77e4045205c64c4aea
