### ISSUE TITLE
implement 'exclude' option in the store and clone operations

### ISSUE THREAD

**Issue by sedlund** [knoxite/knoxite#46]
Need to have the ability to exclude certain patterns when doing backups.

Something like:
`  -e, --exclude pattern         exclude a pattern (can be specified multiple times)`

`knoxite -r /tmp/knoxite -p pass store 47eded9b ~/src --exclude ~/src/github.com `
`knoxite -r /tmp/knoxite -p pass clone 347f7cad ~/src --exclude ~/src/github.com `

**Comment by muesli** [comment]
Exclude for store operations has been added.

**Comment by bganne** [comment]
I am trying to use it to exclude VirtualBox VMs images, stored in '$HOME/VirtualBox VMs/' folder.
I saw it uses filepath.Match(), which seems to exclude using patterns such as '*VirtualBox VMs/*' as '*' does not match accross separator '/'. I also tried to use $(find $HOME/'VirtualBox VMs/' -printf ' -x %p') to exclude the full filenames, using multiple '-x' options without success.
Any hints on how to use this option?

**Comment by muesli** [comment]
@bganne `$HOME` being part of the quoted string might be the problem here. I'm personally using it with multiple exclusion arguments like this:

```
$ knoxite ... -x "/home/muesli/VirtualBox VMs*" -x "cache"
```

Hope that's helpful. Thanks for the kind words, I appreciate your feedback!

**Comment by penguwin** [comment]
resolved in #71

**Comment by muesli** [comment]
Fixed in 5fe65ab3.
