### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [knoxite/knoxite#57]
Dear @knoxite,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by muesli** [comment]
I'll switch to goreleaser for the next release, at which point we'll provide Windows binaries. Until then it's fairly straight-forward to compile a Go program, even on Windows.

Mind you: I don't think anyone's tested knoxite onWindows so far, so I'm not sure I'd recommend it just yet.

**Comment by muesli** [comment]
Switched to goreleaser, builds soon!

**Comment by sergeevabc** [comment]
The issue has been closed, yet no builds exist.

**Comment by muesli** [comment]
See my comments here.

**Comment by sergeevabc** [comment]
> @muesli  
I'll switch to goreleaser for the next release, at which point we'll provide Windows binaries.

It was said in April 2019. Now it’s May 2020, so a year has passed.

**Comment by muesli** [comment]
Sorry, I meant my comment "Switched to goreleaser, builds soon!" from less than 3 weeks ago. Apart from that my comment from last year still holds up: we will provide Windows binaries along with our first release. Until then you'll either have to build/install knoxite manually or speed up things by contributing yourself.
