### ISSUE TITLE
master wont compile, missing dropbox library

### ISSUE THREAD

**Issue by purplesrl** [knoxite/knoxite#58]
Cloning into '/go/src/github.com/stacktic/dropbox'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/stacktic/dropbox: exit status 128

Replacing with this worked:

https://github.com/ncw/dropbox

**Comment by muesli** [comment]
I fear the old Dropbox API may not work anymore, though. We need to switch to a different library altogether here.

**Comment by muesli** [comment]
Fixed by cdaa85a.
